version: "3.7"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    # only if --api.insecure=false
    #   - "443:443"
    # dashboard (for testing only, otherwise check traefik doc for production config)
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    networks:
      - apio-default

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - apio-default

networks:
  apio-default:
    external: yes